(ns active.clojure.test-deps
  (:require [active.clojure.condition-test]
            [active.clojure.config-test]
            [active.clojure.debug-test]
            [active.clojure.freer-monad-test]
            [active.clojure.functions-test]
            [active.clojure.lens-test]
            [active.clojure.macro-test]
            [active.clojure.mock-monad-test]
            [active.clojure.monad-test]
            [active.clojure.record-runtime-test]
            [active.clojure.record-spec-test]
            [active.clojure.record-test]
            [active.clojure.sum-type-test]
            [active.clojure.validation-test]))
