name: ci
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: DeterminateSystems/nix-installer-action@main
    - name: install Clojure dependencies
      run: nix develop -c lein deps
    - name: run Clojure tests
      run: nix develop -c lein test
    - run: PATH="$(pwd):$PATH" nix develop --impure -c lein figtest-headless

  codox:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: DeterminateSystems/nix-installer-action@main
    - run: nix develop -c lein codox
