name: ci
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: add pwd to PATH
      run: echo "$(pwd)" >> "$GITHUB_PATH"
    - name: install Leiningen
      run: |
        curl -LSs https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein -o lein
        chmod +x lein
    - name: install Clojure dependencies
      run: lein deps
    - name: run Clojure tests
      run: lein test
    - run: lein figtest-headless

  codox:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: add pwd to PATH
      run: echo "$(pwd)" >> "$GITHUB_PATH"
    - name: install Leiningen
      run: |
        curl -LSs https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein -o lein
        chmod +x lein
    - run: lein codox

  notify-test-failures:
    runs-on: ubuntu-latest
    needs: [test, codox]
    if: failure() && github.ref == 'refs/heads/main'
    steps:
      - env:
          SECRET: ${{ secrets.MATTERMOST_WEBHOOK_URL }}
          CHANNEL: "active-clojure"
          USERNAME: "GitHub"
        run: |
          URL=https://github.com/${GITHUB_REPOSITORY}/commit/${GITHUB_SHA}
          curl -i --data-urlencode "payload={\"channel\":\"${CHANNEL}\", \"username\":\"${USERNAME}\",\"text\":\"Failure in tests: ${URL}\"}" ${SECRET}
